#ifndef _WELCOME_SMILEYS_H
#define _WELCOME_SMILEYS_H

#include "mm_24.gif.h"
#include "LDSad.bmp.h"
#include "LLAngry.bmp.h"
#include "LRCrying.bmp.h"
#include "LUSmile.bmp.h"
#include "RDDrunk.bmp.h"
#include "RLLaugh.bmp.h"
#include "RRTongue.bmp.h"
#include "RUDefcon.bmp.h"

#include "partyparrot_00_delay-0.04s.gif.h"
#include "partyparrot_01_delay-0.04s.gif.h"
#include "partyparrot_02_delay-0.04s.gif.h"
#include "partyparrot_03_delay-0.04s.gif.h"
#include "partyparrot_04_delay-0.04s.gif.h"
#include "partyparrot_05_delay-0.04s.gif.h"
#include "partyparrot_06_delay-0.04s.gif.h"
#include "partyparrot_07_delay-0.04s.gif.h"
#include "partyparrot_08_delay-0.04s.gif.h"
#include "partyparrot_09_delay-0.04s.gif.h"

#include "frame_00_delay-0.2s.gif.h"
#include "frame_01_delay-0.2s.gif.h"
#include "frame_02_delay-0.2s.gif.h"
#include "frame_03_delay-0.2s.gif.h"
#include "frame_04_delay-0.2s.gif.h"
#include "frame_05_delay-0.2s.gif.h"
#include "frame_06_delay-0.2s.gif.h"
#include "frame_07_delay-0.2s.gif.h"
#include "frame_08_delay-0.2s.gif.h"
#include "frame_09_delay-0.2s.gif.h"
#include "frame_10_delay-0.2s.gif.h"
#include "frame_11_delay-0.2s.gif.h"
#include "frame_12_delay-0.2s.gif.h"
#include "frame_13_delay-0.2s.gif.h"
#include "frame_14_delay-0.2s.gif.h"
#include "frame_15_delay-0.2s.gif.h"
#include "frame_16_delay-0.2s.gif.h"
#include "frame_17_delay-0.2s.gif.h"

#endif
